services:
  - type: web
    name: giotam-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements-render.txt && python startup.py && python migrate_donations.py
    startCommand: gunicorn app:app
    envVars:
      - key: BASE_URL
        value: https://giotam-backend.onrender.com
